#!/usr/bin/env bash
# UPDATE LOG
# 2026-03-17 12:00:00 | Created: cleanup script for temp log files generated by fetch-logs.sh
#
# Usage:
#   bash scripts/ops/clean-logs.sh [--days N] [--dry-run]
#
# Removes files in logs/tmp/ older than N days (default: 1).
# Use --dry-run to preview what would be deleted without actually deleting.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

DAYS=1
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --days)    DAYS="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    *) echo "[ERROR] Unknown argument: $1" >&2; exit 1 ;;
  esac
done

LOGDIR="$ROOT_DIR/logs/tmp"

if [[ ! -d "$LOGDIR" ]]; then
  echo "[INFO]  logs/tmp/ does not exist — nothing to clean."
  exit 0
fi

echo "[INFO]  Scanning logs/tmp/ for files older than ${DAYS} day(s) ..."

DELETED=0
SKIPPED=0

while IFS= read -r -d '' file; do
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  [DRY-RUN] would delete: ${file}"
    DELETED=$((DELETED + 1))
  else
    rm -f "$file"
    echo "  [DELETED] ${file}"
    DELETED=$((DELETED + 1))
  fi
done < <(find "$LOGDIR" -maxdepth 1 -type f -mtime +"$((DAYS - 1))" -print0 2>/dev/null)

while IFS= read -r -d '' file; do
  SKIPPED=$((SKIPPED + 1))
done < <(find "$LOGDIR" -maxdepth 1 -type f -mtime -"$DAYS" -print0 2>/dev/null)

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[INFO]  Dry run complete. Would delete ${DELETED} file(s), keep ${SKIPPED} file(s)."
else
  echo "[OK]    Deleted ${DELETED} file(s). ${SKIPPED} file(s) kept (newer than ${DAYS} day(s))."
fi
