-- P8 hardening follow-up: enable RLS on all public tables that already have policies.
-- Addresses Supabase linter findings: policy_exists_rls_disabled + rls_disabled_in_public.

ALTER TABLE IF EXISTS public.account_deletion_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ats_derivatives ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ats_findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ats_job_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ats_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ats_resumes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ats_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ats_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cost_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_extractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.error_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.log_cleanup_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.log_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.log_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_job_descriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_job_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_resumes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_skill_experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_user_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sats_users_public ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.service_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.system_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.techstack_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.work_experiences ENABLE ROW LEVEL SECURITY;
